app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
homepage:
    path:      /homepage
    defaults:  { _controller: AppBundle:Default:index }
    
another:
    path:      /yo/yo
    defaults:  { _controller: AppBundle:Default:another }